### ISSUE TITLE
What's the purpose of the 'propagate' button ?

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Midas#50]
The default behavior was initially intended that any selection in any browser automatically propagates to all opened browsers. This is a bit similar to MoosePanel where any selection automatically opens a new pane (propagation)

This can be fine-tuned by 'frozing' browsers to ignore this propagation

One could imagine not wanting to always propagate all actions, but then 'propagate' should be a checkbox ...

**Comment by ClotildeToullec** [comment]
It is useful when you want to propagate the current selection without having to unselect-reselect it.
This could be managed differently, in each browser, making the propagate button unnecessary.

**Comment by ClotildeToullec** [comment]
There is another problem with this button: it is always enabled, even when there is no selected entity (this is because spec does not consider #canBeExecuted method when building the button, which is ... annoying).

It allows the propagation of nil or MiNoSelectedElementToPropagateException, which we do not want.

It is possible to manage enabling/disabling the button when an entity is selected but it has to be done in each browser.

**Comment by jordanmontt** [comment]
I will close this since this is not an issue. And it has a little more that a year old :)
